export const GroupArray = [
  {
    id: 1,
    name: "MEE",
    group: 1,
    played: 0,
    won: 0,
    lost: 0,
    draw: 0,
    goalD: 0,
    points: 0,
  },
  {
    id: 2,
    name: "CVE",
    group: 1,
    played: 0,
    won: 0,
    lost: 0,
    draw: 0,
    goalD: 0,
    points: 0,
  },
  {
    id: 3,
    name: "CHE",
    group: 1,
    played: 0,
    won: 0,
    lost: 0,
    draw: 0,
    goalD: 0,
    points: 0,
  },
  {
    id: 4,
    name: "CPE",
    group: 1,
    played: 0,
    won: 0,
    lost: 0,
    draw: 0,
    goalD: 0,
    points: 0,
  },

  {
    id: 5,
    name: "FBE",
    played: 0,
    won: 0,
    lost: 0,
    draw: 0,
    goalD: 0,
    points: 0,
    group: 2,
  },
  {
    id: 6,
    name: "ELE",
    played: 0,
    won: 0,
    lost: 0,
    draw: 0,
    goalD: 0,
    points: 0,
    group: 2,
  },
  {
    id: 7,
    name: "MME",
    played: 0,
    won: 0,
    lost: 0,
    draw: 0,
    goalD: 0,
    points: 0,
    group: 2,
  },
  {
    id: 8,
    name: "BME",
    played: 0,
    won: 0,
    lost: 0,
    draw: 0,
    goalD: 0,
    points: 0,
    group: 2,
  },

  {
    competionName: 400,
    group: [
      {
        groupOne: [
          {
            id: 1,
            name: "MEE",
            group: 1,
            played: 0,
            won: 0,
            lost: 0,
            draw: 0,
            goalD: 0,
            points: 0,
          },
          {
            id: 2,
            name: "CVE",
            group: 1,
            played: 0,
            won: 0,
            lost: 0,
            draw: 0,
            goalD: 0,
            points: 0,
          },
        ],
      },
    ],

    matches: [
      {
        id: "MEECPE",
        matchDay: 1,
        firstteam: "Mechanical Engineering",
        secondteam: "Computer Engineering",
        firstteamScore: 0,
        secondteamScore: 0,
        time: "3:00 PM",
        gamestate: "TBD",
        firstTeamScores: [
          {
            id: 1,
            GoalScorer: "Salako Micheal",
            Assist: "Ibrahim",
            goalType: "Penalty",
          },
          {
            id: 2,
            GoalScorer: "Salako Micheal",
            Assist: "Ibrahim",
            goalType: "Penalty",
          },
        ],
        secondTeamScores: [
          {
            id: 1,
            GoalScorer: "Salako Micheal",
            Assist: "Ibrahim",
            goalType: "Penalty",
          },
          {
            id: 2,
            GoalScorer: "Salako Micheal",
            Assist: "Ibrahim",
            goalType: "Penalty",
          },
        ],
      },

    ],
  },
];
