export const MatchArray = [
  {
    id: "MEECPE",
    matchDay: 1,
    firstteam: "Mechanical Engineering",
    secondteam: "Computer Engineering",
    firstteamScore: 0,
    secondteamScore: 0,
    time: "3:00 PM",
    gamestate: "TBD",
    firstteamScores: [
      {
        id: 1,
        GoalScorer: "Salako Micheal",
        Assist: "Ibrahim",
        goalType: "Penalty",
      },
      {
        id: 2,
        GoalScorer: "Salako Micheal",
        Assist: "Ibrahim",
        goalType: "Penalty",
      },
    ],
  },
  {
    id: "FBEBME",
    matchDay: 1,
    firstteam: "Food / ABE Engineering",
    secondteam: "Biomedical / Water Engineering",
    firstteamScore: 0,
    secondteamScore: 0,
    time: "5:00 PM",
    gamestate: "TBD",
    firstteamScores: [
      {
        id: 1,
        GoalScorer: "Salako Micheal",
        Assist: "Ibrahim",
        goalType: "Penalty",
      },
      {
        id: 2,
        GoalScorer: "Salako Micheal",
        Assist: "Ibrahim",
        goalType: "Penalty",
      },
    ],
  },
  {
    id: "CVECHE",
    matchDay: 1,
    firstteam: "Civil Engineering ",
    secondteam: "Chemical Engineering",
    firstteamScore: 0,
    secondteamScore: 0,
    time: "3:00 PM",
    gamestate: "TBD",
    firstteamScores: [
      {
        id: 1,
        GoalScorer: "Salako Micheal",
        Assist: "Ibrahim",
        goalType: "Penalty",
      },
      {
        id: 2,
        GoalScorer: "Salako Micheal",
        Assist: "Ibrahim",
        goalType: "Penalty",
      },
    ],
  },
  {
    id: "ELEMME",
    matchDay: 1,
    firstteam: "Electrical Engineering",
    secondteam: "Mat & Met Engineering",
    firstteamScore: 0,
    secondteamScore: 0,
    time: "3:00 PM",
    gamestate: "TBD",
    firstteamScores: [
      {
        id: 1,
        GoalScorer: "Salako Micheal",
        Assist: "Ibrahim",
        goalType: "Penalty",
      },
      {
        id: 2,
        GoalScorer: "Salako Micheal",
        Assist: "Ibrahim",
        goalType: "Penalty",
      },
    ],
  },
  {
    id: "MEECHE",
    matchDay: 2,
    firstteam: "Mechanical Engineering",
    secondteam: "Chemical Engineering",
    firstteamScore: 0,
    secondteamScore: 0,
    time: "3:00 PM",
    gamestate: "TBD",
    firstteamScores: [
      {
        id: 1,
        GoalScorer: "Salako Micheal",
        Assist: "Ibrahim",
        goalType: "Penalty",
      },
      {
        id: 2,
        GoalScorer: "Salako Micheal",
        Assist: "Ibrahim",
        goalType: "Penalty",
      },
    ],
  },
  {
    id: "FBEMME",
    matchDay: 2,
    firstteam: "Food / ABE Engineering",
    secondteam: "Mat & Met Engineering",
    firstteamScore: 0,
    secondteamScore: 0,
    time: "5:00 PM",
    gamestate: "TBD",
    firstteamScores: [
      {
        id: 1,
        GoalScorer: "Salako Micheal",
        Assist: "Ibrahim",
        goalType: "Penalty",
      },
      {
        id: 2,
        GoalScorer: "Salako Micheal",
        Assist: "Ibrahim",
        goalType: "Penalty",
      },
    ],
  },
  {
    id: "CVECPE",
    matchDay: 2,
    firstteam: "Civil Engineering",
    secondteam: "Computer Engineering",
    firstteamScore: 0,
    secondteamScore: 0,
    time: "3:00 PM",
    gamestate: "TBD",
    firstteamScores: [
      {
        id: 1,
        GoalScorer: "Salako Micheal",
        Assist: "Ibrahim",
        goalType: "Penalty",
      },
      {
        id: 2,
        GoalScorer: "Salako Micheal",
        Assist: "Ibrahim",
        goalType: "Penalty",
      },
    ],
  },
  {
    id: "ELEBME",
    matchDay: 2,
    firstteam: "Electrical Engineering",
    secondteam: "Biomedical / Water Engineering",
    firstteamScore: 0,
    secondteamScore: 0,
    time: "5:00 PM",
    gamestate: "TBD",
    firstteamScores: [
      {
        id: 1,
        GoalScorer: "Salako Micheal",
        Assist: "Ibrahim",
        goalType: "Penalty",
      },
      {
        id: 2,
        GoalScorer: "Salako Micheal",
        Assist: "Ibrahim",
        goalType: "Penalty",
      },
    ],
  },
  {
    id: "CVEMEE",
    matchDay: 3,
    firstteam: "Civil Engineering",
    secondteam: "Mechanical Engineering",
    firstteamScore: 0,
    secondteamScore: 0,
    time: "3:00 PM",
    gamestate: "TBD",
    firstteamScores: [
      {
        id: 1,
        GoalScorer: "Salako Micheal",
        Assist: "Ibrahim",
        goalType: "Penalty",
      },
      {
        id: 2,
        GoalScorer: "Salako Micheal",
        Assist: "Ibrahim",
        goalType: "Penalty",
      },
    ],
  },
  {
    id: "ELEFBE",
    matchDay: 3,
    firstteam: "Electrical Engineering",
    secondteam: "Food / ABE Engineering",
    firstteamScore: 0,
    secondteamScore: 0,
    time: "5:00 PM",
    gamestate: "TBD",
    firstteamScores: [
      {
        id: 1,
        GoalScorer: "Salako Micheal",
        Assist: "Ibrahim",
        goalType: "Penalty",
      },
      {
        id: 2,
        GoalScorer: "Salako Micheal",
        Assist: "Ibrahim",
        goalType: "Penalty",
      },
    ],
  },
  {
    id: "CPECHE",
    matchDay: 3,
    firstteam: "Computer Engineering",
    secondteam: "Chemical Engineering",
    firstteamScore: 0,
    secondteamScore: 0,
    time: "3:00 PM",
    gamestate: "TBD",
    firstteamScores: [
      {
        id: 1,
        GoalScorer: "Salako Micheal",
        Assist: "Ibrahim",
        goalType: "Penalty",
      },
      {
        id: 2,
        GoalScorer: "Salako Micheal",
        Assist: "Ibrahim",
        goalType: "Penalty",
      },
    ],
  },
  {
    id: "BMEMME",
    matchDay: 3,
    firstteam: "Biomedical / Water Engineering",
    secondteam: "Mat & Met Engineering",
    firstteamScore: 0,
    secondteamScore: 0,
    time: "5:00 PM",
    gamestate: "TBD",
    firstteamScores: [
      {
        id: 1,
        GoalScorer: "Salako Micheal",
        Assist: "Ibrahim",
        goalType: "Penalty",
      },
      {
        id: 2,
        GoalScorer: "Salako Micheal",
        Assist: "Ibrahim",
        goalType: "Penalty",
      },
    ],
  },
];
